#+title: Julia TTFX Snippets
#+author: tecosaur

A collection of TTFX workloads for Julia packages, for longitudinal performance
testing.

*[[https://github.com/tecosaur/Julia-TTFX-Samples/issues/new?template=create-task.yml][Submit a new TTFX task]]*

Manual PRs are also accepted, but I think you'll find the issue-based approach
pretty smooth 😎.

Tasks should be a tiny representative workload that doesn't require network
access or modify the system state beyond creating files in temp and cache
directories.

* Using this collection

TTFX workloads can be found under =tasks/<pkg>/*= each workload consists of a
script (=task.jl=) and a =Project.toml=. When executed, each script will print the
time taken to:

1. Load the package
2. Run the script
3. The total run time

With the format:

#+begin_example
[load time], [run time], [total time] seconds
#+end_example

for example:

#+begin_example
0.1, 0.2, 0.3 seconds
#+end_example

Also take note this is a community effort involving package authors and
 third-party contributions. While we try to ensure the submissions are of a
 reasonable quality, it is always sensible to take precautions when running a
 collection of snippets, such as using containers.

* Historical Record of Benchmarks

Performance of these snippets, tracked since Julia 1.8.0, including data for Julia nightly, alpha, release, and lts are available in this [[repository][https://github.com/JuliaEcosystemBenchmarks/julia-ecosystem-benchmarks/tree/jeb_logs/plots/Julia-TTFX-Snippets]].