name: "🚀 Create new TTFX task"
description: "Submit code for a new TTFX code snippet"
title: "New task (will be automatically retitled)"
labels:
  - 🛠 newtask
body:
  - type: input
    id: primary_package
    attributes:
      label: "Primary package"
      description: "Name of the main Julia package you’re measuring"
      placeholder: "e.g. DataFrames"
    validations:
      required: true

  - type: input
    id: task_name
    attributes:
      label: "Task name"
      description: "A descriptive name for the task"
      placeholder: "e.g. Create table"
    validations:
      required: true

  - type: input
    id: dependencies
    attributes:
      label: "Dependencies (optional)"
      description: "Other packages or dependencies required (comma-separated)"
      placeholder: "e.g. CSV, Tables"
    validations:
      required: false

  - type: input
    id: attribution
    attributes:
      label: "Attribution (optional)"
      description: "A source that needs crediting for the code to be submitted"
      placeholder: "e.g. The DataFrames test suite"
    validations:
      required: false

  - type: textarea
    id: task_code
    attributes:
      label: "Task code"
      description: |
        Paste your minimal Julia code to measure TTFX here.
        Either omit all `using MyPkg` statements, or put them all at the start.

        The code should be the minium required to reach a relevant TTFX output.
      render: julia
      placeholder: |
        MyPkg.dothing()
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        > <sup>Short snippets of code are not copyrightable. Should you submit an original work, you agree you have the right to license the content under the MIT license ([GitHub T&C's D.6](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#6-contributions-under-repository-license)).</sup>
